# Generated by Django 4.2.16 on 2025-04-10 08:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_offer_userdetail'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Offer',
        ),
    ]
